eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8002
spring:
  application:
    name: cmsservice
  datasource:
    url: jdbc:mysql://localhost:3306/wk?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: rootroot
    driverClassName:  com.mysql.jdbc.Driver
    # druid connection pool
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #validationQuery: select 'x'
    #testWhileIdle: true
    #testOnBorrow: false
    #testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  #typeAliasesPackage: com.xdd.entity
mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com:
      wk:
        cms:
          dao:  DEBUG

